server:
  port: 85
  tomcat:
    #配置Tomcat编码，默认为UTF-8
    uri-encoding: UTF-8

logging:
  level:
    com:
      sh:
        mapper: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/topic-01?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root

  redis:
    database: 0       # Redis数据库索引（默认为0）
    host: localhost   # Redis服务器地址
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-idle: 8   # 连接池中的最大空闲连接 默认 8
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        min-idle: 0   # 连接池中的最小空闲连接 默认 0
    password: ''      # Redis服务器连接密码（默认为空）
    port: 6379        # Redis服务器连接端口

#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        hbm2ddl:
#          auto: update
#    show-sql: true

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
